### ISSUE TITLE
iOS Unified API support

### ISSUE THREAD

**Issue by SeeD-Seifer** [brianchance/MvvmCross-UserInteraction#14]
Any plans to support iOS Unified API (and MvvmCross 3.5)?

**Comment by brianchance** [comment]
It is planned, just need to get the time.

**Comment by SeeD-Seifer** [comment]
I can assist with pull-request for iOS and Android. Though no chances to assist with Win projects.

**Comment by brianchance** [comment]
Kind of the same boat I am in, I did not due the windows support. I would take a PR and try to get to it sooner.

**Comment by brianchance** [comment]
I just released a package, hopefully it works :)
