### ISSUE TITLE
Failed to resolve type Chance.MvvmCross.Plugins.UserInteraction.IUserInteraction

### ISSUE THREAD

**Issue by lewis-elliott** [brianchance/MvvmCross-UserInteraction#18]
The instructions on the read me only show installation for installing as a plugin, so I'm not sure where to go from here.

Is there any further setup required after installing it as a nuget package or is this an issue?

The error is:

"Failed to resolve type Chance.MvvmCross.Plugins.UserInteraction.IUserInteraction"

Stack:

"Cirrious.CrossCore.Exceptions.MvxIoCResolveException: Failed to resolve type Chance.MvvmCross.Plugins.UserInteraction.IUserInteraction
  at Cirrious.CrossCore.IoC.MvxSimpleIoCContainer.Resolve (System.Type t) [0x00000] in <filename unknown>:0
  at Cirrious.CrossCore.IoC.MvxSimpleIoCContainer.Resolve[IUserInteraction] () [0x00000] in <filename unknown>:0"

**Comment by brianchance** [comment]
Make sure you have a reference to the dll in your project. The nuget package may not have added it correctly.

**Comment by BrianSouza** [comment]
I had the same problem. And since removed and added the package and the problem continues.

**Comment by ilfat** [comment]
I have this problem to.
